services:
  - type: web
    name: wargavci-iuran
    runtime: docker
    plan: free
    branch: master
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: APP_NAME
        value: WargaVCI
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: APP_TIMEZONE
        value: Asia/Jakarta
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: info
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: wargavci-iuran-db
          property: connectionString
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: SESSION_DRIVER
        value: file
      - key: FILESYSTEM_DISK
        value: local
      - key: MAIL_MAILER
        value: log

databases:
  - name: wargavci-iuran-db
    plan: free
